site_name: Updater Wiki

# Repository Configuration
repo_url: https://github.com/Vxrpenter/Updater
repo_name: Updater

# Theming
theme:
  name: material
  language: en

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light-green
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode


    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light-green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  logo: assets/logo-no-background.png

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

  features:
    - content.action.edit
    - navigation.tabs
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - toc.integrate

extra:
  version:
    provider: mike

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Vxrpenter/Updater
    - icon: fontawesome/solid/book
      link: https://vxrpenter.github.io/updater/
    - icon: fontawesome/solid/paper-plane
      link: https://github.com/Vxrpenter#%EF%B8%8F-contact-me-

plugins:
  - mike
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Setup:
    - Installation: setup/installation.md
    - Logging: setup/logging.md
  - Using Updater:
    - Getting Started: using-updater/index.md
    - Update Schemas: using-updater/update-schemas.md
    - Upstreams: using-updater/upstreams.md
    - Versions: using-updater/versions.md
    - Configuration: using-updater/configuration.md
    - Current Version: using-updater/current-version.md
  - KDoc: https://vxrpenter.github.io/updater/
